### ISSUE TITLE
Dates in johns-hopkins-format do not match JHU's date format

### ISSUE THREAD

**Issue by lazd** [AnthonyEbert/ItalyCovid19#1]
The dates in the column headers do not match the format of the JHU dates -- yours are zero padded.

**Comment by AnthonyEbert** [comment]
I can't work out an easy way to do this. Would you share your code?

**Comment by lazd** [comment]
@AnthonyEbert sure, [here it is](https://github.com/lazd/coronaglobe/blob/italyregions/tools/generateCasesByLocation.js#L74-L78). I'm doing it in JavaScript, though, and it's relatively easy to do there. I'll see if I can fix it in your R code and submit a pull request.
